{
 "title": "TimescaleDB",
 "time": { "from": "now-40d", "to": "now-20d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Slowest Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  page,\n  avg(duration) AS \"duration\"\nFROM measurements\nWHERE\n  $__timeFilter(event_time)\nGROUP BY 1, page\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_time,$__interval,previous),\n  avg(duration) AS \"duration\"\nFROM measurements\nWHERE\n  $__timeFilter(event_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_time,$__interval,previous),\n  count(*)\nFROM measurements\nWHERE\n  $__timeFilter(event_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Latency by Page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_time,$__interval),\n  page,\n  avg(duration) AS \"duration\"\nFROM measurements\nWHERE\n  $__timeFilter(event_time)\nGROUP BY 1, page\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Latency by Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_time,$__interval),\n  method,\n  avg(duration) AS \"duration\"\nFROM measurements\nWHERE\n  $__timeFilter(event_time)\nGROUP BY 1, method\nORDER BY 1"
    }
   ]
  }
 ]
}